# This file was generated by the `rspec --init` command.
RSpec.configure do |config|
  # rspec-expectations config
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # This setting enables warnings
  config.warnings = true

  # Run specs in random order
  config.order = :random

  # Seed global randomization
  Kernel.srand config.seed
end
